### PR TITLE
Fix CAS 4 upgrade compatibility to CAS 6

### LINKED ISSUE #123: Upgrade from CAS4 to CAS6 fails with old doguctl version
If you upgrade from a CAS 4 dogu which has an old `doguctl` version built in, the upgrade process to CAS 6 fails if doguctl does not provide the `doguctl config --remove` function. This function is used in the pre-upgrade script: https://github.com/cloudogu/cas/blob/develop/resources/pre-upgrade.sh#L25

### PR DESCRIPTION
**Pull request by robertauer**
- Get CAS 4 upgrade compatibility by moving upgrade steps to post-upgrade script
- Resolves #123

### CODE REVIEW

File: resources/pre-upgrade.sh [hunk 1]
```diff
@@ -3,55 +3,17 @@ set -o errexit
...
 
-checkSameVersion
-removeDeprecatedKeys
-migrateServiceAccounts
+echo "Set registry flag so startup script waits for post-upgrade to finish..."
+doguctl state "upgrading"
 
-echo "Executing CAS pre-upgrade from ${FROM_VERSION} to ${TO_VERSION} ... Done!"
\ No newline at end of file
+echo "Redmine pre-upgrade done"
```
Comment (nhinze23) [inline resources/pre-upgrade.sh:19]: Cas pre-upgrade done

File: resources/post-upgrade.sh [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+}
+
+function migrateServiceAccounts() {
+  echo "Migrating service service_accounts..."
+  VALUE=$(doguctl config service_accounts/portainer --default "default" || true)
+  if [[ "${VALUE}" != "default" ]]; then
+      {
+        CLIENT_SECRET="$(doguctl config service_accounts/portainer)"
+        doguctl config --remove service_accounts/portainer
+        doguctl config service_accounts/oauth/portainer "${CLIENT_SECRET}"
```
Comment (nhinze23) [inline resources/post-upgrade.sh:45]: VALUE can be used here
